# mongod.conf

storage:
  dbPath: /data/db

net:
  port: 27017
  # Use 0.0.0.0 to allow connections from other containers
  bindIp: 0.0.0.0

#security:
  # This is recommended for production
#  authorization: disabled

processManagement:
  fork: false # Let Docker handle the process
  
#log:
#  destination: "stdout"