events {
	worker_connections 1024;
}
http{
	types {
		application/javascript js;
		text/html html;
		text/css css;
		image/png png;
		image/jpeg jpg jpeg;
		image/gif gif;
		image/svg+xml svg svgz;
		application/font-woff woff;
		application/font-woff2 woff2;
	}
	server {
		listen       9000;
		server_name  axo-ui;
		port_in_redirect off;

		location /axo {
			return 302 /axo/;
		}
		location /axo/ {
			alias /usr/share/nginx/html/;
			#root   /usr/share/nginx/html;
			#index  index.html index.htm;
			try_files $uri $uri/ /axo/index.html;
		}

		error_page   500 502 503 504  /50x.html;
		location = /50x.html {
			root   /usr/share/nginx/html;
		}
	}

}